server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

logging:
  file: /data/logs/fadmin-auth.log
  level:
    org.springframework.web: info
    f.s: debug

spring:
  datasource:
    url: jdbc:mysql://192.168.0.229:3306/fadmin_auth?characterEncoding=UTF8&useSSL=false
    username: root
    password: XJS@#2018
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  #redis配置
  redis:
    database: 0
    host: 192.168.0.229
    port:  6379
    timeout: 6000

service:
  permService:
    url: http://fadmin-perm

