server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: fadmin-common

logging:
  file: /data/logs/fadmincommon.log
  level:
    org.springframework.web: debug
    f.s: debug
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p -- [%t] %-40.40logger{39} : %m%n%xEx{10}'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p -- [%t] %-40.40logger{39} : %m%n%xEx{10}'

service:
  permService:
    url: http://fadmin-perm